<a href="https://colab.research.google.com/github/Kavyabv123/numpy/blob/main/numpy_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[[4,3,6]],[[6,8,4]],[[8,10,12]],[[12,16,18]]])

In [ ]:
np.ndim(arr)

3

In [ ]:
np.sort(arr)

array([[[ 3,  4,  6]],

       [[ 4,  6,  8]],

       [[ 8, 10, 12]],

       [[12, 16, 18]]])

In [ ]:
np.where(arr==4)

(array([0, 1]), array([0, 0]), array([0, 2]))

In [6]:
np.where(arr==[12,16,18])

(array([3, 3, 3]), array([0, 0, 0]), array([0, 1, 2]))